Repository oqtopus-team/device-gateway, pull requests merged in 2025-03, with the labels that each got.

#1 Add MkDocs documentation and contribution guidelines
  Makefile
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  docs/index.md
  mkdocs.yaml
  pyproject.toml
  uv.lock
Labels: feature

#3 Add Read the Docs configuration for documentation build
  .readthedocs.yaml
Labels: documentation

#5 Simplify uv sync command in Read the Docs configuration
  .readthedocs.yaml
Labels: bugfix

#6 Update README and index files for Device Gateway documentation
  README.md
  docs/image/device_gateway.png
  docs/index.md
  mkdocs.yaml
Labels: documentation

#19 feat: Add a Dockerfile with a simple, minimal set of tools installed for development
  Dockerfile.dev
Labels: feature

#21 Update DOI badge in README and documentation
  README.md
  docs/index.md
Labels: bugfix

#22 Bump version to 1.0.0 and update asset paths
  CITATION.cff
  mkdocs.yaml
  pyproject.toml
  uv.lock
Labels: chore

#24 Replace OQTOPUS logo with banner
  README.md
  docs/asset/oqtopus-banner.png
  docs/asset/oqtopus_logo.png
  docs/index.md
Labels: bugfix, feature

#27 Update device topology JSON and initialize QPU v1 module
  config/device_topology.json
  src/device_gateway/gen/qpu/v1/__init__.py
Labels: bugfix, feature
